Repository flashflashrevolution/rCubed, pull requests merged in 2020-06, with the labels that each got.

#67 Add "Play Random Button" To GameResults Screen
  src/GlobalVariables.as
  src/game/GameResults.as
Labels: enhancement

#79 Workflow: Rename master to main
  .github/workflows/check.yml
Labels: bug

#78 Temporarily remove the reverse mod.
  src/GlobalVariables.as
Labels: bug

#76 Prevent repeating the first song in queue
  src/menu/MenuSongSelection.as
Labels: bug, enhancement

#80 Bump release version and build timestamp.
  application.xml
  asconfig.release.json
  changelog.txt
Labels: release

#75 Add checkbox for vertically flipping the marker result graph
  src/game/GameResults.as
  src/popups/PopupOptions.as
Labels: enhancement

#84 Create pull-request-notification.yml
  .github/workflows/pull-request-notification.yml
Labels: workflow

#83 Add platforms badge, and fixed up shortlinks.
  README.md
Labels: documentation

#87 Highlight personal best scores
  src/menu/MenuSongSelection.as
  src/popups/PopupHighscores.as
Labels: enhancement

#90 Skip over inaccessible songs during menu navigation
  src/menu/MenuSongSelection.as
Labels: enhancement

#93 Add rcubed-contributors to CODEOWNERS
  .github/CODEOWNERS
Labels: documentation, enhancement

#91 Make division level array static
  src/arc/ArcGlobals.as
  src/arc/mp/MultiplayerChat.as
  src/arc/mp/MultiplayerPanel.as
Labels: enhancement

#92 Update shortlink header comments
  README.md
Labels: documentation, enhancement

#88 Update pull-request-notification.yml
  .github/workflows/pull-request-notification.yml
Labels: workflow

#85 Version values supplied by CI rather than hard-coded in repository. (#70)
  .github/workflows/check.yml
  .github/workflows/release.yml
  application.xml
  asconfig.release.json
Labels: workflow

#97 Fix for multiplayer room join bug
  src/com/flashfla/net/Multiplayer.as
Labels: bug

#101 Run formatter over files that were missed.
  src/com/flashfla/net/DynamicURLLoader.as
  src/com/flashfla/net/ForcibleLoader.as
  src/com/flashfla/net/MP3Loader.as
  src/com/flashfla/net/MultipartURLLoader.as
  src/com/flashfla/net/Multiplayer.as
  src/com/flashfla/net/PHPLoader.as
  src/com/flashfla/net/SWFLoader.as
  src/com/flashfla/net/WebRequest.as
  src/com/flashfla/net/events/MultipartURLLoaderEvent.as
Labels: documentation, enhancement

#96 Enable editing songs in the current queue
  src/menu/MenuSongSelection.as
Labels: enhancement

#95 Implement Websocket Support for Game Status
  src/GlobalVariables.as
  src/Main.as
  src/be/aboutme/airserver/AIRServer.as
  src/be/aboutme/airserver/Client.as
  src/be/aboutme/airserver/endpoints/IClientHandler.as
  src/be/aboutme/airserver/endpoints/IEndPoint.as
  src/be/aboutme/airserver/endpoints/socket/SocketEndPoint.as
  src/be/aboutme/airserver/endpoints/socket/handlers/SocketClientHandler.as
  src/be/aboutme/airserver/endpoints/socket/handlers/SocketClientHandlerFactory.as
  src/be/aboutme/airserver/endpoints/socket/handlers/websocket/WebSocketClientHandler.as
  src/be/aboutme/airserver/endpoints/socket/handlers/websocket/WebSocketClientHandlerFactory.as
  src/be/aboutme/airserver/events/AIRServerEvent.as
  src/be/aboutme/airserver/events/EndPointEvent.as
  src/be/aboutme/airserver/events/MessageReceivedEvent.as
  src/be/aboutme/airserver/events/MessagesAvailableEvent.as
  src/be/aboutme/airserver/messages/Message.as
  src/be/aboutme/airserver/messages/serialization/IMessageSerializer.as
  src/be/aboutme/airserver/messages/serialization/JSONSerializer.as
  src/game/GamePlay.as
  src/popups/PopupOptions.as
Labels: enhancement

#102 "MP Connection Lost" hidden while in solo
  src/com/flashfla/net/Multiplayer.as
  src/game/GamePlay.as
Labels: bug

#100 Refactor Song Selection and Song Item
  src/Constant.as
  src/menu/MenuSongSelection.as
  src/menu/SongItem.as
  src/menu/SongItemLocked.as
Labels: enhancement

#99 Gray out "Save Replay" button rather than hide it
  src/game/GameResults.as
Labels: enhancement

#94 Changelog for v1.2.3
  changelog.txt
Labels: release

#105 Remove unused analytics from flash days.
  src/GlobalVariables.as
  src/menu/MainMenu.as
Labels: bug

#103 Start building both release and debug
  .github/workflows/check.yml
Labels: bug

#107 Flip result graph when switching graph type
  src/game/GameResults.as
Labels: bug

#109 Update changelog for v1.2.4 release (hotfix)
  changelog.txt
Labels: release

#110 Remove config blocks for air and not_air.
  asconfig.json
  asconfig.release.json
  src/AirContext.as
  src/Constant.as
  src/GlobalVariables.as
  src/Main.as
  src/classes/chart/Song.as
  src/com/flashfla/utils/SystemUtil.as
  src/game/GamePlay.as
  src/game/GameResults.as
  src/menu/MainMenu.as
  src/menu/MenuSongSelection.as
  src/popups/PopupFilterManager.as
  src/popups/PopupOptions.as
  src/popups/PopupReplayHistory.as
Labels: documentation, enhancement

#111 Add Additional Combo Color Options
  src/classes/User.as
  src/game/GameOptions.as
  src/game/GamePlay.as
  src/game/controls/Combo.as
  src/popups/PopupOptions.as
Labels: enhancement

#117 Keep language strings in options menu up-to-date
  src/popups/PopupOptions.as
Labels: bug

#119 Remove old Flash version checks
  src/GlobalVariables.as
  src/com/flashfla/utils/ObjectPool.as
  src/com/flashfla/utils/RollingAverage.as
  src/game/GamePlay.as
  src/popups/PopupCustomNoteskin.as
  src/popups/PopupOptions.as
Labels: enhancement
